# Generated by Django 4.0.6 on 2022-07-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='name',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
