# Generated by Django 4.0.6 on 2022-07-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schedulemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemodel',
            name='name',
        ),
    ]
