# Generated by Django 4.0.6 on 2022-07-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_schedulemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
