# Generated by Django 4.0.6 on 2022-07-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_moviemodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='when',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='movie_reliased',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='main.moviemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
