# Generated by Django 4.0.6 on 2022-07-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_moviemodel_when_moviemodel_movie_reliased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='age',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='time',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
