# Generated by Django 4.0.6 on 2022-07-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_moviemodel_age_moviemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
