# Generated by Django 4.0.6 on 2022-07-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_moviemodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='is_part_of_slide',
            field=models.BooleanField(default=False),
        ),
    ]
