# Generated by Django 4.0.6 on 2022-07-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_moviemodel_is_part_of_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='is_part_of_slide',
            new_name='is_part_of_banner',
        ),
    ]
