# Generated by Django 4.0.6 on 2022-07-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactmodel_delete_contatctmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
